export {
  BUILD_DOC_VERSION,
  FOOD_BUFF_SLOTS,
  MAX_ACTIVE_SKILLS,
  TREE_KEYS,
  activeSkillCount,
  activeSupportLinks,
  emptyBuild,
  isAuraEnabled,
  isFoodBuffEnabled,
  isSkillEnabled,
  isSupportEnabled,
  supportLinks,
} from "./build-doc.js";
export type {
  AffixRoll,
  AuraSetup,
  BuildConfig,
  BuildDoc,
  BuildMeta,
  BuildStage,
  EffectSetup,
  EnemySetup,
  FoodBuffSetup,
  FoodBuffSlot,
  MobOffence,
  ExileEffectSetup,
  Item,
  Jewel,
  OmenSetup,
  SkillSetup,
  SupportLink,
  TargetPlacement,
  TreeCoord,
  TreeKey,
} from "./build-doc.js";

export {
  DEFAULT_STAGE_NAME,
  IMPLICIT_STAGE_ID,
  activeStage,
  addStage,
  applyStage,
  ensureStages,
  mainStage,
  normalizeStages,
  removeStage,
  renameStage,
  setMainStage,
  stageContent,
  stageDoc,
  stageList,
  syncStages,
} from "./stages.js";
export type { StageContent } from "./stages.js";

export {
  TARGET_PRESETS,
  availableRarities,
  buildTargetEnemy,
  isTargetPresetId,
  targetPreset,
} from "./target-presets.js";
export type { TargetPreset, TargetPresetId } from "./target-presets.js";

export {
  ELEMENTS,
  ELEMENT_GUIDS,
  ELEMENT_NAMES,
  SINGLE_ELEMENTAL,
  CONVERTED_ELEMENTS,
  SINGLE_ELEMENTS,
  elementByGuid,
  elementByName,
  elementsMatch,
  isSingleElement,
  isValidElement,
} from "./elements.js";
export type { ElementName, ElementView } from "./elements.js";

export {
  AFFIX_TYPES,
  CATEGORY,
  DEFAULT_BALANCE_ID,
  DEFAULT_PLAYER_BASE_STATS_ID,
  affix,
  affixAllowedOnTags,
  affixCount,
  affixesFor,
  allowedAffixTiers,
  baseGearType,
  basesForSlot,
  entry,
  gearRarity,
  has,
  ids,
  EPILOGUE_BONUS_POINTS,
  infusionRollPercent,
  rarityLadder,
  isAffixType,
  isJewelStyle,
  isKnownReqType,
  JEWEL_STYLES,
  jewelAffixesFor,
  jewelCorruptionAffixes,
  jewelTags,
  MAX_EYE_AURA_STATS,
  MAX_JEWEL_CORRUPTIONS,
  watcherEyeAffixes,
  WATCHER_EYE_UNIQUE,
  maxBonusSpellLevels,
  maxLevel,
  maxOfOneAffixType,
  meetsTagRequirement,
  perk,
  perksOfKind,
  pointBudget,
  playerPointBudget,
  pointsAvailable,
  pointsPerLevel,
  PLAYER_POINT_TYPES,
  serverConfigList,
  serverConfigNumber,
  slotFamily,
  treeGrid,
  TREE_POINT_TYPE,
  unique,
  uniquesForBase,
  CORE_STAT_SER,
  FAMILY_CAPACITY,
  SLOT_CAPACITY,
  TWO_HANDED_TAG,
  allUniques,
  coreStatIds,
  enchantCompats,
  attributeName,
  enchantName,
  isTwoHanded,
  maxQuality,
  slotCapacity,
  slotFamilyCapacity,
  statPointBudget,
  uniqueRarityId,
  GEAR_RARITY_TYPES,
  countOmenPieces,
  isGearRarityType,
  omen,
  omenAffixRoll,
  omenBuckets,
  omenCountsSlot,
  omenIds,
  omenMinLevel,
  omenStatMulti,
  omenStatPercent,
  gem,
  rune,
  runeword,
  runewordFitsBase,
  runewordMatches,
  runewordsForItem,
  socketFamily,
  socketFamilyOfBase,
  statsForFamily,
} from "./queries.js";
export type {
  AffixType,
  AffixView,
  BaseGearTypeView,
  EnchantCompatView,
  GemView,
  RuneView,
  RunewordView,
  SocketFamily,
  StatRequirementDecl,
  GearRarityView,
  JewelStyle,
  MinMax,
  PerkView,
  PlayerPointType,
  PointBudget,
  PointsAvailable,
  TagRequirement,
  TreeCell,
  TreeCellKind,
  GearRarityTypeName,
  OmenBucket,
  OmenView,
  TreeGrid,
  UniqueView,
} from "./queries.js";

export {
  allocationBlock,
  canAllocate,
  hasPathToEntry,
  nodeKey,
  orphansIfRemoved,
  parseNodeKey,
  shortestPathTo,
  treeGraph,
} from "./tree-graph.js";
export type {
  AllocationBlock,
  NodeKey,
  TreeEdge,
  TreeGraph,
  TreeNode,
} from "./tree-graph.js";

export {
  DEFAULT_JEWEL_STYLE,
  LANG_KEY,
  MC_COLOURS,
  MC_COLOUR_NAMES,
  SHEET_GROUPS,
  UNCATEGORISED,
  affixName,
  auraName,
  compareForSheet,
  sheetGroupName,
  sheetGroupOf,
  sheetGroupRank,
  exileEffectName,
  fillTemplate,
  formatNumber,
  formatted,
  gearTypeName,
  hasText,
  humanise,
  isTemplate,
  itemBaseName,
  itemName,
  jewelItemId,
  jewelName,
  modifierLine,
  modifierValue,
  parseFormatting,
  gemName,
  perkName,
  rarityName,
  runeName,
  runewordName,
  itemSetName,
  mobAffixName,
  omenName,
  slotName,
  spellDesc,
  spellName,
  statBuffName,
  statDesc,
  statDisplay,
  statLayerName,
  statName,
  statNameRaw,
  stripFormatting,
  stripGlossaryMarkup,
  supportGemName,
  text,
  underAugmentLabel,
  uniqueName,
} from "./display.js";
export type { SheetGroup, Span, StatDisplay } from "./display.js";

export {
  importFailed,
  importItem,
  parseStatLine,
  rarityNameIndex,
  rollFromDisplay,
  statNameIndex,
} from "./import-item.js";
export type { ImportIssue, ImportResult, ImportSeverity } from "./import-item.js";

export {
  isDeprecatedSpell,
  isMercenarySpell,
  isWizardSpell,
  mercenarySpellIds,
  playerSpellFor,
  playerSpellIds,
  spellExclusion,
  wizardSpellIds,
} from "./spell-roster.js";
export type { SpellExclusion } from "./spell-roster.js";

export {
  LEARN_STAT_PREFIX,
  MAX_SCHOOLS,
  SOLO_CLASS_DAMAGE_REDUCTION,
  SOLO_CLASS_MORE_DAMAGE,
  allocatedSchools,
  isSoloClass,
  isSpellPerk,
  learnedSpells,
  levelNeededForNextPerkLevel,
  perkPointType,
  schoolOfPerk,
  schoolPerksInOrder,
  schoolPointsSpent,
  spellOfPerk,
  spellSchool,
  spellSchoolIds,
  unknownSchoolPerks,
} from "./spell-schools.js";
export type { SchoolPoint, SpellSchoolView } from "./spell-schools.js";

export { isLegal, validateBuild } from "./validate.js";
export type { Diagnostic, Severity, ValidateOptions } from "./validate.js";

export {
  COMPARED_FIELDS,
  EXACT,
  FIELD_TOLERANCE,
  HALF_POINT,
  MOD_DUMP,
  OBSERVATION_SOURCES,
  TRUNCATION_SLACK,
  TWO_DECIMALS,
  compareFixture,
  parseFixture,
  toleranceFor,
} from "./fixture.js";
export type {
  ComparedField,
  CompareOptions,
  ComparisonStatus,
  ComputedDamage,
  ComputedStat,
  DamageCalculator,
  Fixture,
  FixtureResult,
  Observation,
  ObservationSource,
  ObservedAilmentEvent,
  ObservedDamage,
  ObservedDamageEvent,
  ObservedLayer,
  ObservedMore,
  ObservedSource,
  ObservedStat,
  ObservedWeapon,
  StatCalculator,
  StatComparison,
  Tolerance,
} from "./fixture.js";

/**
 * `Stat`'s own fields, and the table of the ones Mine and Slash registers only in Java.
 *
 * These live here rather than in `@cte2/engine` because `statDisplay` needs them: a code-only
 * stat has no JSON, so its `is_perc` is reachable from nowhere else, and the Stats tab was
 * printing Shatter Chance and Shock Chance as bare numbers. The engine re-exports both names,
 * so nothing that imported them from there had to change.
 */
export {
  MAX_FLOAT,
  MULTI_USE_TYPES,
  STAT_DEFAULTS,
  STAT_SCALINGS,
  isMultiUseType,
  isStatScaling,
} from "./stat-shape.js";
export type { MultiUseType, StatScaling, StatShape } from "./stat-shape.js";
export {
  CODE_ONLY_CLASS_SHAPES,
  CODE_ONLY_STATS,
  CODE_ONLY_TRANSFERS,
} from "./code-only-stats.generated.js";
