export {
  BUILD_DOC_VERSION,
  FOOD_BUFF_SLOTS,
  MAX_ACTIVE_SKILLS,
  TREE_KEYS,
  activeSkillCount,
  emptyBuild,
  isAuraEnabled,
  isFoodBuffEnabled,
  isSkillEnabled,
  supportLinks,
} from "./build-doc.js";
export type {
  AffixRoll,
  AuraSetup,
  BuildConfig,
  BuildDoc,
  BuildMeta,
  EffectSetup,
  EnemySetup,
  FoodBuffSetup,
  FoodBuffSlot,
  MobOffence,
  ExileEffectSetup,
  Item,
  Jewel,
  OmenSetup,
  SkillSetup,
  SupportLink,
  TargetPlacement,
  TreeCoord,
  TreeKey,
} from "./build-doc.js";

export {
  TARGET_PRESETS,
  availableRarities,
  buildTargetEnemy,
  isTargetPresetId,
  targetPreset,
} from "./target-presets.js";
export type { TargetPreset, TargetPresetId } from "./target-presets.js";

export {
  ELEMENTS,
  ELEMENT_GUIDS,
  ELEMENT_NAMES,
  SINGLE_ELEMENTAL,
  CONVERTED_ELEMENTS,
  SINGLE_ELEMENTS,
  elementByGuid,
  elementByName,
  elementsMatch,
  isSingleElement,
  isValidElement,
} from "./elements.js";
export type { ElementName, ElementView } from "./elements.js";

export {
  AFFIX_TYPES,
  CATEGORY,
  DEFAULT_BALANCE_ID,
  DEFAULT_PLAYER_BASE_STATS_ID,
  affix,
  affixAllowedOnTags,
  affixCount,
  affixesFor,
  allowedAffixTiers,
  baseGearType,
  basesForSlot,
  entry,
  gearRarity,
  has,
  ids,
  isAffixType,
  isKnownReqType,
  maxBonusSpellLevels,
  maxLevel,
  maxOfOneAffixType,
  meetsTagRequirement,
  perk,
  perksOfKind,
  pointBudget,
  playerPointBudget,
  pointsAvailable,
  pointsPerLevel,
  PLAYER_POINT_TYPES,
  serverConfigList,
  serverConfigNumber,
  slotFamily,
  treeGrid,
  TREE_POINT_TYPE,
  unique,
  uniquesForBase,
  CORE_STAT_SER,
  FAMILY_CAPACITY,
  SLOT_CAPACITY,
  TWO_HANDED_TAG,
  allUniques,
  coreStatIds,
  isTwoHanded,
  slotCapacity,
  slotFamilyCapacity,
  statPointBudget,
  uniqueRarityId,
  GEAR_RARITY_TYPES,
  countOmenPieces,
  isGearRarityType,
  omen,
  omenBuckets,
  omenCountsSlot,
  omenIds,
  omenMinLevel,
  omenStatMulti,
  omenStatPercent,
  gem,
  rune,
  runeword,
  runewordFitsBase,
  runewordMatches,
  runewordsForItem,
  socketFamily,
  socketFamilyOfBase,
  statsForFamily,
} from "./queries.js";
export type {
  AffixType,
  AffixView,
  BaseGearTypeView,
  GemView,
  RuneView,
  RunewordView,
  SocketFamily,
  StatRequirementDecl,
  GearRarityView,
  MinMax,
  PerkView,
  PlayerPointType,
  PointBudget,
  PointsAvailable,
  TagRequirement,
  TreeCell,
  TreeCellKind,
  GearRarityTypeName,
  OmenBucket,
  OmenView,
  TreeGrid,
  UniqueView,
} from "./queries.js";

export {
  allocationBlock,
  canAllocate,
  hasPathToEntry,
  nodeKey,
  orphansIfRemoved,
  parseNodeKey,
  shortestPathTo,
  treeGraph,
} from "./tree-graph.js";
export type {
  AllocationBlock,
  NodeKey,
  TreeEdge,
  TreeGraph,
  TreeNode,
} from "./tree-graph.js";

export {
  LANG_KEY,
  MC_COLOURS,
  MC_COLOUR_NAMES,
  SHEET_GROUPS,
  UNCATEGORISED,
  affixName,
  auraName,
  compareForSheet,
  sheetGroupName,
  sheetGroupOf,
  sheetGroupRank,
  exileEffectName,
  fillTemplate,
  formatNumber,
  gearTypeName,
  hasText,
  humanise,
  isTemplate,
  modifierLine,
  modifierValue,
  parseFormatting,
  gemName,
  perkName,
  rarityName,
  runeName,
  runewordName,
  slotName,
  spellDesc,
  spellName,
  statBuffName,
  statDesc,
  statDisplay,
  statLayerName,
  statName,
  statNameRaw,
  stripFormatting,
  supportGemName,
  text,
  uniqueName,
} from "./display.js";
export type { SheetGroup, Span, StatDisplay } from "./display.js";

export {
  importFailed,
  importItem,
  parseStatLine,
  rarityNameIndex,
  rollFromDisplay,
  statNameIndex,
} from "./import-item.js";
export type { ImportIssue, ImportResult, ImportSeverity } from "./import-item.js";

export {
  LEARN_STAT_PREFIX,
  MAX_SCHOOLS,
  SOLO_CLASS_DAMAGE_REDUCTION,
  SOLO_CLASS_MORE_DAMAGE,
  allocatedSchools,
  isSoloClass,
  isSpellPerk,
  learnedSpells,
  levelNeededForNextPerkLevel,
  perkPointType,
  schoolOfPerk,
  schoolPerksInOrder,
  schoolPointsSpent,
  spellOfPerk,
  spellSchool,
  spellSchoolIds,
  unknownSchoolPerks,
} from "./spell-schools.js";
export type { SchoolPoint, SpellSchoolView } from "./spell-schools.js";

export { isLegal, validateBuild } from "./validate.js";
export type { Diagnostic, Severity, ValidateOptions } from "./validate.js";

export {
  COMPARED_FIELDS,
  EXACT,
  FIELD_TOLERANCE,
  HALF_POINT,
  MOD_DUMP,
  OBSERVATION_SOURCES,
  TRUNCATION_SLACK,
  TWO_DECIMALS,
  compareFixture,
  parseFixture,
  toleranceFor,
} from "./fixture.js";
export type {
  ComparedField,
  CompareOptions,
  ComparisonStatus,
  ComputedDamage,
  ComputedStat,
  DamageCalculator,
  Fixture,
  FixtureResult,
  Observation,
  ObservationSource,
  ObservedDamage,
  ObservedDamageEvent,
  ObservedLayer,
  ObservedMore,
  ObservedSource,
  ObservedStat,
  ObservedWeapon,
  StatCalculator,
  StatComparison,
  Tolerance,
} from "./fixture.js";
